### ISSUE TITLE
OA-II VEH TAM structure change 

### ISSUE THREAD

**Issue by Carton9** [orangerbt/ORBiT-documentation#7]
@gjsmo 
I would like to merge the Low-Speed Sensor Board and High-Speed Sensor Board to the General Data Acquisition Unit. The new unit will contain one FPGA which use for translation and encoding to the backplane bus and a multi-purpose extension interface.  The interface can connect to other PCB board which contain sensors.

**Comment by gjsmo** [comment]
Completed in #8.
